name: conejoz
description: Dream journal.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.7.2
  firebase_storage: ^11.2.5
  image_picker: ^1.0.1
  http: ^1.1.0
  path_provider: ^2.0.15
  firebase_ui_auth: ^1.6.2
  get: ^4.6.5
  flutter_native_splash: ^2.3.1
  loading_indicator: ^3.1.1
  intl: ^0.18.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/images/conejoz-prototype-96-light.png
  image_dark: assets/images/conejoz-prototype-96-dark.png

  android_12:
    image: assets/images/conejoz-prototype-96-light.png
    icon_background_color: "ffffff"
    image_dark: assets/images/conejoz-prototype-96-dark.png
    icon_background_color_dark: "#000000" 

flutter:
  uses-material-design: true
  assets:
     - assets/images/conejoz-prototype-96-light.png
     - assets/images/conejoz-prototype-96-dark.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: ConejozLogos
    fonts:
      - asset: assets/fonts/ConejozLogos.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
